import React from "react";

const Disclaimers = () => {
	return(
		<>
             <section className="main">
        <div className="container disclaimer">
          <div className="row">
            <div className="col-md-1" />
            <div className="col-md-10">
              <h2 className="text-center">Disclaimers and Disclosures</h2>
              <p className="p4">1.	www.Unlistedassets.com is operated by Unlisted Tech Private Limited. We are not a trading platform and provide only technology platform in the form of marketplace for buying and selling shares/stocks of unlisted companies in India. </p> 
              <p className="p4">2.	www.unlistedassets.com which is operated by Unlisted Tech Private Limited provide only its platform and act as a facilitator and does not give to its users any guidance, advisory or recommendation to buy a particular stock from this website and therefore, www.unlistedassets.com does not act an advisor for its users. The users, whether they be, buyers or sellers, before buying or selling any unlisted security from www.unlistedassets.com should hold consultations with their advisors (financial/legal), if required, before doing any transaction on the platform. The user must undertake their own research of the prevailing market/industry situation and other relevant considerations before buying or selling unlisted securities at www.unlistedassets.com. </p> 
<p className="p4">3.	You confirm that you have decided to make investment on www.unlistedassets.com after fully understanding the platform features and about the target securities and associated risk with such investment(s), applicable charges, and keeping in mind your financial position and risk appetite.  </p> 
<p className="p4">4.	To facilitate transactions, Unlisted Tech Private Limited has partnered with SEBI registered Trustee and Nationalised Bank as Escrow Bank for any transaction executed on the platform to provide the security of the funds deposited in the escrow account. Unlisted Tech Private Limited will not be responsible for any claim which user may have against the Escrow Bank for amount transferred and not reflected in their respective user account solely on account of banking transaction failure.  </p> 
<p className="p4">5.	 www.unlistedassets.com is not responsible for any loss arising out of buying or selling of the unlisted shares on account of any change in market/industry condition(s) or economic environment or for other reasons unless directly attributable to Unlisted Tech Private Limited.  </p> 
<p className="p4">6.	www.unlistedassets.com is NEITHER a Stock Broker NOR a Stock Exchange as defined by the Securities Exchange Board of India (SEBI) under the Securities Contract (Regulation) Act, 1956. Nothing on www.unlistedassets.com constitute an offer to buy or sell unlisted securities.  </p> 
<p className="p4">7.	You as a user of www.unlistedassets.com in either capacity, of buyer or of seller, acknowledge and confirm that you fully understand the features of www.unlistedassets.com and its platform and the risk(s) entailed in buying unlisted shares from platforms such as www.unlistedassets.com owned and operated by Unlisted Tech Private Limited. </p> 
<p className="p4">8.	You as user in either capacity, of buyer or of seller acknowledge, confirm and undertake that you have not been influenced or are being influenced, neither have you been given any assurance/guarantee of any fixed returns to you out of the investment you undertake in unlisted securities by any of the employees, directors, associates, partners, agents, representatives, or relationship managers of Unlisted Tech Private Limited. </p> 
<p className="p4">9.	You as user, in either capacity of a buyer or of seller, fully understand that www.unlistedassets.com or its associate, affiliate, distributor, partner companies, employees act as referral or distributor and they are not responsible in any case for any loss arising out of investments facilitated by Unlisted Tech Private Limited on its website/platform, www.unlistedassets.com.  </p> 
<p className="p4">10.	You as user, in either capacity of a buyer or of seller, agree to indemnify Unlisted Tech Private Limited or www.unlistedassets.com, its subsidiaries or parent company, if any, its promoters, distributors, affiliates and employees harmless from any claim, demand or damage, including reasonable attorney’s fee. </p> 
<p className="p4">11.	You as user, in either capacity of a buyer or of seller, confirm that you are making the payment towards purchase of shares or any other product on www.unlistedassets.com through your own bank account and from source of income which is legal in India.   </p> 
<p className="p4">12.	You as a user in either capacity of buyer or seller fully acknowledge and understand that investing in unlisted shares/securities through websites like www.unlistedassets.com is not suitable for some investors who may have a lower risk appetite as there is no liquid market for unlisted stock(s) being traded in the market and price fluctuation also take place on account of demand supply mismatch at most of the times. </p> 
<p className="p4">13.	You as a user in either capacity of buyer or seller acknowledge that investing in an unlisted company’s security may entail high degree of risk as the same are highly volatile and dealing in them should only be considered after consulting investment advisor(s). </p> 
<p className="p4">14.	You as a buyer or seller fully acknowledge and understand that after buying unlisted shares, you may face the loss in your investments as unlisted company’s securities are highly illiquid and there is no guarantee that a liquid market will develop for such securities. </p> 
<p className="p4">15.	You as a user in either capacity of a buyer or seller acknowledge, confirm and understand that investing in unlisted securities entails specific types of risk common to such types and investments and that you should invest only post your own independent due diligence regarding the investment, including obtaining additional information about the company, historical financials, financial projections and legal or other investment advice, as may be required. It may be noted that there could be limited information in public domain for unlisted companies for any investor to take an informed decision on investment in unlisted shares.  </p> 
<p className="p4">16.	You as a user in either capacity of a buyer or seller, acknowledge and understand that investing in unlisted companies’ securities may be inappropriate for those investors who cannot tolerate a high degree of risk and have preference of making liquid investments with fixed returns. </p> 
<p className="p4">17.	You as a buyer or seller declare and confirm to complying with all laws and regulations as applicable under Foreign Exchange Management Act, 2000 (FEMA) as amended from time to time, under Companies act 2013 or any other applicable laws relating to buying/selling of unlisted shares in India. In the event of any violation of any laws, you as buyer or seller take complete responsibility and shall be held responsible for any legal consequences. </p> 
<p className="p4">18.	We don’t do any valuation of unlisted shares traded on our platform or www.unlistedassets.com. We offer only information in public domain which may be relevant to the users for the purpose of taking any decision as to the investments without any guarantee of any sufficiency or adequacy or correctness of any data sourced from public domain for which the user are expected to hire an expert through us or otherwise for which we claim no responsibility and the user will always keep us indemnified against claim in future, if any, arising from any reason attributable to the information posted on platform or taken from expert.   </p> 
<p className="p4">19.	Use of www.unlistedassets.com or its platform is subject to terms and conditions, privacy policy, disclosures, as well as various notices, flags, notifications, rules and procedure which may be displayed on www.unlistedassets.com or shared individually with the Buyer or Seller on the platform during the course of transaction or from time to time. Your use of the platform and www.unlistedassets.com and its services serve as your acknowledgement and acceptance of these terms, conditions and disclaimers.   </p>   
<p className="p4">20.	The content and data available on www.unlistedassets.com, including but not limited to news update, research reports, etc are for information and reference/illustration purposes only and should not by any means be considered as an investment advice. Unlisted Tech Private Limited does not guarantee the correctness or accuracy of the information provided on its website www.unlistedassets.com. A user in either capacity of a buyer or seller is expected to do the proper due diligence before buying/selling the unlisted securities from the www.unlistedassets.com. </p> 
<p className="p4">21.	In case of any reports or update sourced from other database and posted on the website of Unlisted Tech Private Limited, we will not have any obligation towards the completeness or correctness of such information. We advise user to do their due diligence before relying on such information posted on the website www.unlistedassets.com for their reference only. We will not be liable for any loss of investment or otherwise, directly or indirectly, for relying on such information.  </p> 
<p className="p4">22.	While the buyer can find on the website a description of certain securities, however, the description on the website is taken from the official website of Ministry of Corporate Affairs (MCA) and other sources which are publicly available and the Unlisted Tech Private Limited is not responsible for the accuracy of such data and information sourced from public domain. </p> 
<p className="p4">23.	The user in either capacity of a buyer or seller shall be responsible for any non-performance or any other breach of contract entered into between Unlisted Tech Private Limited and such party or between buyer and seller. </p> 
<p className="p4">24.	You as a user in either capacity of a buyer or seller, fully acknowledge and understand that past performance of any unlisted stock does not guarantee future returns from such stocks. Investments in such unlisted stocks are always subject to market/industry risks and investors should read all the related information or documents carefully before investing in such unlisted stocks. </p> 
<p className="p4">25.	Support - Contact us on hello@unlistedassets.com for any queries and assistance. </p> 


            </div>
            <div className="col-md-1" />
          </div>			
        </div>
      </section>
		</>
	);
}

export default Disclaimers;