import React from "react";



const PrivacyPolicy = () => {
  return (
    <>
      <section className="section privacy-policy">
        <div className="container">
          <div className="row">
            <div className="col-md-2" />
            <div className="col-md-8">
              <h2 className="text-center heading">Privacy Policy</h2>
              <p className="p4">
                This privacy policy describes our policy and procedures on collection, use and disclosure of your information when you use the Services and tells you about your privacy rights and how the law protects you.
              </p>
              <p className="p4">
                We use your personal data to provide and improve the Service through our platform. By using the service of our platform, you agree to the collection and use of information in accordance with this privacy policy. This privacy policy has been with the help of generator. We can use your data such as email, mobile number, social media communication etc., to offer you services related to our domain of services through our platform or our associate or affiliate or subsidiaries.
              </p>
              <h4>Interpretations</h4>
              <p className="p4">
                The words of which initial letter is capitalized have meaning defined as under. The following defintions shall have the same meaning regardless of whether they appear in singular or plural
              </p>
              <h4>Definitions</h4>
              <p className="p4">For the purpose of this Policy:</p>
              <ul>
                <li>You mean individual accessing or using the services, or company or another legal entity on behalf of which the individual is using or accessing the services, as applicable.</li>
                <li>The Company or We or Us refers to Unlisted Tech private Limited or its group company, partners, associate, or affiliate</li>
                <li>Affiliate means an entity that controls or is controlled by or under common control with a party where &ldquo;Control&rdquo; means ownership of the some of the shares, equity interest or securities entitled to vote for election of Directors or other managing authority or he is referral or distribution partner with any of the group companies</li>
                <li>Distributors: Those who have shown their desire or interest to work with us</li>
                <li>Partner Companies: Where we have working relationship</li>
                <li>Account means account created for you to access our services</li>
                <li>Bank Account means virtual bank account created for you to access the transaction on our Platform</li>
                <li>Website refers <a href="http://www.unlistedassets.com">www.unlistedassets.com</a> or any other website added by the company</li>
                <li>Service refers to marketplace related services, technical or otherwise, for the consummation of transaction on the Platform</li>
                <li>Country means India unless specially mentioned otherwise</li>
                <li>Service provider means any natural or legal person who processes data on the behalf of the Company in relation to the Services. It refers to the third party companies or employees engaged by the Company to perform or facilitate the Services</li>
                <li>Third party social media Service means any website or social network website through which user may log in or caret an account to access the Service</li>
                <li>Personal data refer to the data that pertains to identified or identifiable individual</li>
                <li>Cookies are the small files which are placed on Your Computer, mobile device or any other device by a website containing the details of the browsing history on that website among its users</li>
                <li>Usage data refers to the data collected automatically, either generated by the use of Service or from the service infrastructure itself </li>
              </ul>
              <h3 className="heading">Collecting and using Your Personal Data</h3>
              <p className="p4">Types of data collected</p>

              <h4>Personal data</h4>
              <p className="p4">While using our services, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include </p>
              <ul>
                <li>Email address</li>
                <li>First and last name</li>
                <li>Phone number</li>
                <li>Address, State, Province, Zip code, City, District</li>
                <li>Usage data</li>
                <li>Social media like facebook, whatsapp, Linkedin, Titter, etc</li>
              </ul>
              <h4>Usage data</h4>

              <p>Usage data may include information such as your device Internet Protocol address, browser type, browser version, pages of our service that you visit, time and date of your visit, the time spent on those pages, unique device identifier and other diagnostic data. When you access the service by or through a mobile device, we may collect certain information automatically, including but not limited to type of mobile device you use, Your mobile device unique ID, IP address of your mobile device, your mobile operating system, the type of mobile internet browser you use, unique device identifiers and other diagnostic data. We may also collect information that your browser send whenever you visit our service or when you access the service by or through a mobile device. When you access our platform, we can use any of your available information.</p>

              <h4>Tracking technologies and cookies</h4>

              <p>We use cookies and similar technologies to track the activity on our service and store your information. Tracking technologies used are beacons, tags, scripts, to collect and track information and to improve and analyze our Service. You can instruct your browser to refuse all cookies or indicate when a cookie is being send. However, if you don&rsquo;t accept any cookies, you may not be able to use some parts of our service. Cookies can be persistent or Session cookies. Persistent cookies remain on your computer or mobile device when you go offline while Session cookies are deleted as soon as you close browser. We use both session and persistent cookies</p>


              <h4>Necessary/Essential Cookies</h4>
              <p>Type: Session cookies<br />
Administrated by: US<br />
Purpose: These cookies are essential to provide you with Service available through the website and to enable you to use some of its feature. They help to authenticate users and prevent fraudulent use of user accounts. Without these cookies, the services that you have asked for cannot be provided, and we only use these cookies to provide you with those services.</p>

              <h4>Cookies policy/notice Acceptance cookies</h4>
              <p>Type: Persistent Cookies <br />
Administrated by: US<br />
Purpose: These cookies identify if users have accepted the use of cookies on the website</p>

              <h4>Functionality Cookies</h4>
              <p>Type: persistent cookies<br />
Administrated by: US<br />
Purpose: These cookies allow us to remember choice you make when you the website such as remembering your login details or language preference. The purpose of these cookies is to provide you with a more personal experience and to avoid having to re-enter your preference every time when you log in.</p>

              <h4>Log Files</h4>

              <p>We follow a standard procedure of using log files. These file log visitors when they visit websites. All hosting companies do this and a part of hosting services analytics. The information collected by log files include IP addresses, browser type, ISP, date and time stamp, referring/exit page, and possibly the number of clicks. These are not linked to any information that is not identifiable. The purpose of this information is for analyzing trends, administrating the site, tracking users movement on the website and gathering demographic information.</p>

              <h4>Use of your Personal data</h4>
              <p>The Company may use the Personal data for the following purposes:</p>
              <ul>
                <li>To provide and maintain our service: including to monitor the usage of our service</li>
                <li>To manage your account: to manage your registration as user of the Service. The personal data you provide can give access to different functionalities of the Service that are available to you as a registered user</li>
                <li>For the performance of a contract: the development compliance and undertaking of the purchase contract for the product item or service you have purchased or of any other contract wit us through the service</li>
                <li>To contact you: To contact by email, email, telephone calls, SMS or other equivalent form of electronics communications such as mobile applications push notifications regarding update or informative communications related to the functionalities, product or contracted services, including security updates, when required or reasonable for their implementation  </li>
                <li>To provide you with news, special offers, and general information about other product services and event which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information</li>
                <li>To manage Your request or to offer different product or services: to attend and manage your request to us</li>
                <li>We may share your personal information in the following situations:</li>
                <li>With Service providers: We may share your personal information with our service providers to monitor and analyze the use of our service, to show advertisement to you to help support and maintain our service, to contact you, to advertise on third party websites to you after you visited our service or for payment processing</li>
                <li>For Business transfer: We nay share or transfer your personal information in connection with or during negotiation of any merger, sale of company assets, financing or acquisition of all or a portion of our busines to another company</li>
                <li>With affiliates: We may share your information with our affiliates in which we will require those affiliates to honor this Privacy policy. Affiliates include parent company, subsidiaries, joint venture partner, or any other company that is controlled by us or is in common control with us</li>
                <li>With business partners: we may share your personal information with our business partner to offer you certain product      </li>
                <li>With other users: when you share your personal information or otherwise interact in the public areas with other users such information may be viewed by all users and may be publicly distributed outside. If you interact with other users or register through a third party social media service, your contact on the third party social media service may see your name, profile, pictures and description, of your activity. Similarly, other users will be able to view descriptions of your activity communicate with you and view your profile.  </li>
              </ul>


              <h4>Third Party Privacy Policies</h4>

              <p>Our privacy policy does not apply to other advertisers or website. Thus, you may consult your advisor on the respective privacy policies of these third parties ad servers for more detailed information. It may include their practices and instruction on how to opt out of certain options.
You can choose to disable cookies through your individual browser options. To know more about cookie management with specific web browser, it can be found at the browser&rsquo;s respective websites.</p>

              <h4>You rights in relation to your personal data Rights</h4>
              <p>We take reasonable steps that are designed to keep your personal data accurate complete and up to date for the purpose for which it is collected and used and to ensure that processing of your personal data complies with applicable laws.<br />
Right to access: You have right to request copies of your personal information. We may charge you a small amount of fee for this.<br />
The right to rectifications: you have the right to request that we correct any information that you believe is incorrect. You also have the right to request that we complete the information that you believe is incomplete.<br />
Right to erase: You have the right to request that your information may be erased under certain specific situations<br />
Right to restrict processing: You have the right to request that we restrict the usage of your personal data under certain situations<br />
Right to object to processing: You have the right to object to our processing of your personal information under certain conditions<br />
Right to data portability: you have right to request that we transfer the data that we have collected to another organization or directly to you under certain situation.<br />
If you make any such request, we will revert back within 15 days. </p>

              <h4>Users</h4>

              <p>If you are coming from United State of America or European union or any other region with laws governing law collection and use, please note that you are agreeing to the transfer of your information to us and processing globally. By providing your information, you consent to any transfer or processing in accordance with this privacy policy. The onus of compliance with the requisite laws applicable in a specific country will resp on the person accessing our services.</p>

              <h4>Retention of your personal data</h4>

              <p>The Company will retain your personal data only for as long as is necessary for the purpose set out in this Privacy policy. We will retain and use your personal data only to the extent necessary to comply with our legal obligations, resolve dispute, and enforce our legal agreement and policies. The Company will also retain data for internal analysis purpose. Usage data is generally retained for a shorter period of time except when this data is retained to strengthen the security or to improve the functionality of our service or we are under some legal obligation to retain it for longer period. </p>

              <h4>Transfer of your personal data</h4>

              <p>Your information including personal data is processing at the company operating offices and in any other places where the parties involved in the processing of the data are located in. This means the information may be transferred to and maintained on computer located outside of you state, province or country or government jurisdiction where the data protection laws may differ than those from your jurisdiction. Your consent to this privacy policy followed by your submission of such information represents your agreement to that transfer. The company will take all steps reasonably necessary to ensure that your data is treated securely and in accordance with this privacy policy and no transfer of your personal data will take place to an organization or a country unless there are adequate control in place including security of your data and personal information.</p>

              <h4>Security of Your personal data</h4>

              <p>The security of your personal data is important to us, but it may be noted that no method of transmission over the internet or method of electronics storage is 100% secure. While we strive to use commercially acceptable means to protect your personal data, we cannot guarantee its absolute security.</p>

              <h4>Children's Privacy</h4>



              <p>Our service does not address anyone under the age of 18. We don't knowingly collect personally identifiable information from anyone under the age of 18. If you are parent or guardian and you are aware that your child has provided us with the personal data, you may please contact us. If we become aware that we have collected personal data from anyone under the age of 18 without verification of parental consent, we take steps to remove that information from our records</p>

              <h4>Changes to this Privacy Policy</h4>

              <p>We may change this privacy policy from time to time and will keep posting the updated policy on this page. You are advised to review the privacy policy periodically for any changes. Changes to this policy are effective when posted on this website. We may also notify of any change in privacy policy via email or any other mode of electronic communication.</p>

              <h4>New Use of Personal Information</h4>

              <p>From time to time we may desire to use personal information for the users not previously disclosed in our privacy policy. If our practice change regarding previously collected personal information in a way that would be materially less restrictive than stated in the version of this privacy policy in effect at the time we collected the information, we will make reasonable efforts to provide notice and obtain consent to any such uses as may be required by law.</p>

              <h4>Contact us:</h4>

              <p>If you have any query on the privacy policy, you may contact us on hello@unlistedassets.com</p>

            </div>
            <div className="col-md-2" />
          </div>
        </div>
      </section>
    </>
  );
}

export default PrivacyPolicy;